# Module 5: Session Management
# OpenAPI specification for session operations, teacher and resource assignments

paths:
  /classes/{class_id}/sessions:
    get:
      tags:
        - Sessions
      summary: Get sessions by class
      description: Retrieve all sessions for a specific class with optional filtering
      operationId: getSessionsByClass
      parameters:
        - name: class_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - $ref: './openapi-schemas.yaml#/components/parameters/DateFromParam'
        - $ref: './openapi-schemas.yaml#/components/parameters/DateToParam'
        - name: status
          in: query
          schema:
            $ref: './openapi-schemas.yaml#/components/schemas/SessionStatusEnum'
        - name: type
          in: query
          schema:
            $ref: './openapi-schemas.yaml#/components/schemas/SessionTypeEnum'
        - $ref: './openapi-schemas.yaml#/components/parameters/PageParam'
        - $ref: './openapi-schemas.yaml#/components/parameters/LimitParam'
      responses:
        '200':
          description: List of sessions
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/SessionDTO'
                  pagination:
                    $ref: './openapi-schemas.yaml#/components/schemas/Pagination'

  /sessions/{id}:
    get:
      tags:
        - Sessions
      summary: Get session details
      description: Retrieve detailed session information including teachers, resources, and students
      operationId: getSessionById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Session details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDetailDTO'
        '404':
          $ref: './openapi-schemas.yaml#/components/responses/NotFoundError'

    put:
      tags:
        - Sessions
      summary: Update session
      description: Update session details (requires MANAGER or ACADEMIC_STAFF role)
      operationId: updateSession
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSessionRequest'
      responses:
        '200':
          description: Session updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionDTO'
        '400':
          $ref: './openapi-schemas.yaml#/components/responses/ValidationError'
        '403':
          $ref: './openapi-schemas.yaml#/components/responses/ForbiddenError'
        '404':
          $ref: './openapi-schemas.yaml#/components/responses/NotFoundError'

  /sessions/{id}/cancel:
    post:
      tags:
        - Sessions
      summary: Cancel session
      description: Cancel a session with reason (requires MANAGER role)
      operationId: cancelSession
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
                  description: Reason for cancellation
              required:
                - reason
      responses:
        '200':
          description: Session cancelled successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int64
                  status:
                    type: string
                  teacher_note:
                    type: string
                  students_notified:
                    type: integer
                  updated_at:
                    type: string
                    format: date-time
        '403':
          $ref: './openapi-schemas.yaml#/components/responses/ForbiddenError'
        '404':
          $ref: './openapi-schemas.yaml#/components/responses/NotFoundError'

  /sessions/{session_id}/teachers:
    post:
      tags:
        - Sessions
      summary: Assign teacher to session
      description: Assign a teacher with specific skill and role (requires MANAGER role)
      operationId: assignTeacher
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignTeacherRequest'
      responses:
        '201':
          description: Teacher assigned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeachingSlotDTO'
        '400':
          $ref: './openapi-schemas.yaml#/components/responses/ValidationError'
        '403':
          $ref: './openapi-schemas.yaml#/components/responses/ForbiddenError'
        '409':
          description: Teacher conflict detected
          content:
            application/json:
              schema:
                $ref: './openapi-schemas.yaml#/components/responses/ConflictError'

    delete:
      tags:
        - Sessions
      summary: Remove teacher from session
      description: Remove teacher assignment (requires MANAGER role)
      operationId: removeTeacher
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: teacher_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: skill
          in: query
          description: Required if teacher teaches multiple skills in this session
          schema:
            $ref: './openapi-schemas.yaml#/components/schemas/SkillEnum'
      responses:
        '204':
          description: Teacher removed successfully
        '403':
          $ref: './openapi-schemas.yaml#/components/responses/ForbiddenError'
        '404':
          $ref: './openapi-schemas.yaml#/components/responses/NotFoundError'

  /sessions/{session_id}/available-teachers:
    get:
      tags:
        - Sessions
      summary: Get available teachers for session
      description: Find teachers available for this session by skill and schedule
      operationId: getAvailableTeachers
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: skill
          in: query
          schema:
            $ref: './openapi-schemas.yaml#/components/schemas/SkillEnum'
      responses:
        '200':
          description: List of available teachers
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AvailableTeacherDTO'

  /sessions/{session_id}/resources:
    post:
      tags:
        - Sessions
      summary: Assign resource to session
      description: Assign room or virtual resource (requires MANAGER role)
      operationId: assignResource
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AssignResourceRequest'
      responses:
        '201':
          description: Resource assigned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResourceDTO'
        '400':
          $ref: './openapi-schemas.yaml#/components/responses/ValidationError'
        '403':
          $ref: './openapi-schemas.yaml#/components/responses/ForbiddenError'
        '409':
          $ref: './openapi-schemas.yaml#/components/responses/ConflictError'

    delete:
      tags:
        - Sessions
      summary: Remove resource from session
      operationId: removeResource
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: resource_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Resource removed successfully
        '403':
          $ref: './openapi-schemas.yaml#/components/responses/ForbiddenError'
        '404':
          $ref: './openapi-schemas.yaml#/components/responses/NotFoundError'

  /sessions/{session_id}/available-resources:
    get:
      tags:
        - Sessions
      summary: Get available resources for session
      description: Find resources available for this session time slot
      operationId: getAvailableResources
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: resource_type
          in: query
          schema:
            $ref: './openapi-schemas.yaml#/components/schemas/ResourceTypeEnum'
      responses:
        '200':
          description: List of available resources
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/AvailableResourceDTO'

components:
  schemas:
    SessionDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        class_id:
          type: integer
          format: int64
        course_session_id:
          type: integer
          format: int64
        date:
          type: string
          format: date
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        type:
          $ref: './openapi-schemas.yaml#/components/schemas/SessionTypeEnum'
        status:
          $ref: './openapi-schemas.yaml#/components/schemas/SessionStatusEnum'
        course_session:
          $ref: './openapi-schemas.yaml#/components/schemas/CourseSessionReference'
        teachers:
          type: array
          items:
            type: object
            properties:
              teacher_id:
                type: integer
                format: int64
              teacher_name:
                type: string
              skill:
                $ref: './openapi-schemas.yaml#/components/schemas/SkillEnum'
              role:
                $ref: './openapi-schemas.yaml#/components/schemas/TeachingRoleEnum'
        resources:
          type: array
          items:
            $ref: './openapi-schemas.yaml#/components/schemas/ResourceReference'
        attendance_summary:
          $ref: './openapi-schemas.yaml#/components/schemas/AttendanceSummary'
        teacher_note:
          type: string
          nullable: true
        created_at:
          type: string
          format: date-time

    SessionDetailDTO:
      allOf:
        - $ref: '#/components/schemas/SessionDTO'
        - type: object
          properties:
            class:
              $ref: './openapi-schemas.yaml#/components/schemas/ClassReference'
            students:
              type: array
              items:
                type: object
                properties:
                  student_id:
                    type: integer
                    format: int64
                  student_code:
                    type: string
                  student_name:
                    type: string
                  is_makeup:
                    type: boolean
                  attendance_status:
                    $ref: './openapi-schemas.yaml#/components/schemas/AttendanceStatusEnum'

    UpdateSessionRequest:
      type: object
      properties:
        date:
          type: string
          format: date
        start_time:
          type: string
          format: time
        end_time:
          type: string
          format: time
        status:
          $ref: './openapi-schemas.yaml#/components/schemas/SessionStatusEnum'
        teacher_note:
          type: string

    AssignTeacherRequest:
      type: object
      properties:
        teacher_id:
          type: integer
          format: int64
        skill:
          $ref: './openapi-schemas.yaml#/components/schemas/SkillEnum'
        role:
          $ref: './openapi-schemas.yaml#/components/schemas/TeachingRoleEnum'
      required:
        - teacher_id
        - skill
        - role

    TeachingSlotDTO:
      type: object
      properties:
        session_id:
          type: integer
          format: int64
        teacher_id:
          type: integer
          format: int64
        teacher_name:
          type: string
        skill:
          $ref: './openapi-schemas.yaml#/components/schemas/SkillEnum'
        role:
          $ref: './openapi-schemas.yaml#/components/schemas/TeachingRoleEnum'
        created_at:
          type: string
          format: date-time

    AvailableTeacherDTO:
      type: object
      properties:
        teacher_id:
          type: integer
          format: int64
        teacher_name:
          type: string
        employee_code:
          type: string
        skills:
          type: array
          items:
            $ref: './openapi-schemas.yaml#/components/schemas/TeacherSkill'
        availability:
          type: object
          properties:
            day_of_week:
              type: integer
            start_time:
              type: string
              format: time
            end_time:
              type: string
              format: time
            is_available:
              type: boolean
        current_sessions_on_date:
          type: integer
        is_ot_registered:
          type: boolean

    AssignResourceRequest:
      type: object
      properties:
        resource_type:
          $ref: './openapi-schemas.yaml#/components/schemas/ResourceTypeEnum'
        resource_id:
          type: integer
          format: int64
        capacity_override:
          type: integer
          nullable: true
          description: Override default capacity if needed
      required:
        - resource_type
        - resource_id

    SessionResourceDTO:
      type: object
      properties:
        session_id:
          type: integer
          format: int64
        resource_type:
          $ref: './openapi-schemas.yaml#/components/schemas/ResourceTypeEnum'
        resource_id:
          type: integer
          format: int64
        resource_name:
          type: string
        capacity:
          type: integer
        capacity_override:
          type: integer
          nullable: true
        created_at:
          type: string
          format: date-time

    AvailableResourceDTO:
      type: object
      properties:
        resource_id:
          type: integer
          format: int64
        resource_type:
          $ref: './openapi-schemas.yaml#/components/schemas/ResourceTypeEnum'
        resource_name:
          type: string
        capacity:
          type: integer
        is_available:
          type: boolean
        conflicts:
          type: array
          items:
            type: object
            properties:
              session_id:
                type: integer
                format: int64
              class_code:
                type: string
              start_time:
                type: string
                format: time
              end_time:
                type: string
                format: time
